name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.13.0'
      - run: mv .env.sample .env.prod
      - run: yarn install
      - run: yarn build
