name: Cypress E2E Admin Side
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-e2e-admin-side:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.13.0'
      - run: mv .env.sample .env
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/admin_basic.cy.js
          start: yarn server:start, yarn start
          wait-on: 'http://localhost:3000'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: cypress-videos
#          path: cypress/videos
