name: Typecheck
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.13.0'
      - run: yarn install
      - run: yarn all:typecheck
